# -*- coding: utf-8 -*-
"""Vina_docking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Vdx0A25gZ0td-xiMZlVq5cbJnPTnsxK
"""

# docking center based on MycB binding results using PyMOL
# see Supplementary Information of https://doi.org/10.1021/jacs.0c12404
# Center: (145.332, 171.816, 195.8805)
# Raw pocket extents: ~23 × 27 × 28 Å
# With +18 Å padding: ~41 × 45 × 46 Å

from __future__ import annotations

import argparse
import csv
import glob
import os
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Tuple

AFFINITY_RE = re.compile(r"^\s*1\s+(-?\d+(?:\.\d+)?)\s+")  # row 1 affinity in kcal/mol

@dataclass
class DockResult:
    ligand: str
    status: str
    best_affinity: Optional[float]
    log_path: str
    out_path: str
    stderr_tail: Optional[str] = None

def parse_best_affinity_from_log(log_text: str) -> Optional[float]:
    """
    Parse the affinity of mode 1 from Vina output.
    Vina prints a table like:
       1 -7.4 0.000 0.000
    """
    for line in log_text.splitlines():
        m = AFFINITY_RE.match(line)
        if m:
            try:
                return float(m.group(1))
            except ValueError:
                return None
    return None

def run_vina(
    vina_bin: str,
    receptor_pdbqt: Path,
    ligand_pdbqt: Path,
    out_pdbqt: Path,
    log_txt: Path,
    center: Tuple[float, float, float],
    size: Tuple[float, float, float],
    exhaustiveness: int,
    num_modes: int,
    energy_range: int,
    cpu: int,
    seed: Optional[int],
    extra_args: List[str],
) -> DockResult:
    cmd = [
        vina_bin,
        "--receptor", str(receptor_pdbqt),
        "--ligand", str(ligand_pdbqt),
        "--out", str(out_pdbqt),
        "--log", str(log_txt),
        "--center_x", str(center[0]),
        "--center_y", str(center[1]),
        "--center_z", str(center[2]),
        "--size_x", str(size[0]),
        "--size_y", str(size[1]),
        "--size_z", str(size[2]),
        "--exhaustiveness", str(exhaustiveness),
        "--num_modes", str(num_modes),
        "--energy_range", str(energy_range),
        "--cpu", str(cpu),
    ]

    if seed is not None:
        cmd += ["--seed", str(seed)]

    if extra_args:
        cmd += extra_args

    try:
        proc = subprocess.run(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            check=False,
        )
    except FileNotFoundError as e:
        return DockResult(
            ligand=ligand_pdbqt.name,
            status="VINA_NOT_FOUND",
            best_affinity=None,
            log_path=str(log_txt),
            out_path=str(out_pdbqt),
            stderr_tail=str(e),
        )

    # Write to log 

    log_text = ""
    if log_txt.exists():
        try:
            log_text = log_txt.read_text(encoding="utf-8", errors="replace")
        except Exception:
            log_text = ""
    if not log_text:
        log_text = (proc.stdout or "") + "\n" + (proc.stderr or "")

    best_aff = parse_best_affinity_from_log(log_text)

    status = "OK" if proc.returncode == 0 and best_aff is not None else f"ERROR_{proc.returncode}"
    stderr_tail = (proc.stderr or "")[-600:] if proc.stderr else None

    return DockResult(
        ligand=ligand_pdbqt.name,
        status=status,
        best_affinity=best_aff,
        log_path=str(log_txt),
        out_path=str(out_pdbqt),
        stderr_tail=stderr_tail,
    )

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--vina", required=True, help="Path to vina binary (e.g., vina or vina.exe)")
    ap.add_argument("--receptor", required=True, type=Path, help="Receptor PDBQT")
    ap.add_argument("--ligands_dir", type=Path, help="Directory containing ligand PDBQT files")
    ap.add_argument("--ligands_glob", help='Glob pattern for ligand PDBQTs (e.g. "ligands/*.pdbqt")')
    ap.add_argument("--out_dir", required=True, type=Path, help="Output directory")

    ap.add_argument("--center", nargs=3, required=True, type=float, metavar=("X", "Y", "Z"))
    ap.add_argument("--size", nargs=3, required=True, type=float, metavar=("SX", "SY", "SZ"))

    ap.add_argument("--exhaustiveness", type=int, default=16)
    ap.add_argument("--num_modes", type=int, default=10)
    ap.add_argument("--energy_range", type=int, default=3)
    ap.add_argument("--cpu", type=int, default=os.cpu_count() or 4)
    ap.add_argument("--seed", type=int, default=None)

    ap.add_argument("--extra", nargs=argparse.REMAINDER, default=[],
                    help='Extra args passed to vina after "--". Example: --extra --scoring vina --verbosity 1')

    args = ap.parse_args()

    receptor = args.receptor
    if not receptor.exists():
        print(f"Receptor not found: {receptor}", file=sys.stderr)
        return 2

    args.out_dir.mkdir(parents=True, exist_ok=True)

    # Collect ligands
    ligand_paths: List[Path] = []
    if args.ligands_glob:
        ligand_paths = [Path(p) for p in glob.glob(args.ligands_glob)]
    elif args.ligands_dir:
        ligand_paths = sorted(args.ligands_dir.glob("*.pdbqt"))
    else:
        print("Provide either --ligands_dir or --ligands_glob", file=sys.stderr)
        return 2

    if not ligand_paths:
        print("No ligand PDBQT files found.", file=sys.stderr)
        return 2

    center = (args.center[0], args.center[1], args.center[2])
    size = (args.size[0], args.size[1], args.size[2])

    results: List[DockResult] = []

    for lig in ligand_paths:
        stem = lig.stem
        out_pdbqt = args.out_dir / f"{stem}_out.pdbqt"
        log_txt = args.out_dir / f"{stem}.log"

        res = run_vina(
            vina_bin=args.vina,
            receptor_pdbqt=receptor,
            ligand_pdbqt=lig,
            out_pdbqt=out_pdbqt,
            log_txt=log_txt,
            center=center,
            size=size,
            exhaustiveness=args.exhaustiveness,
            num_modes=args.num_modes,
            energy_range=args.energy_range,
            cpu=args.cpu,
            seed=args.seed,
            extra_args=args.extra,
        )
        results.append(res)

        # Print affinity
        if res.best_affinity is not None:
            print(f"{res.ligand}: {res.best_affinity:.2f} kcal/mol [{res.status}]")
        else:
            print(f"{res.ligand}: (no score parsed) [{res.status}]")
            if res.stderr_tail:
                print(f"  stderr tail: {res.stderr_tail}", file=sys.stderr)

    # Write summary CSV
    summary_csv = args.out_dir / "vina_summary.csv"
    with summary_csv.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["ligand", "status", "best_affinity_kcal_per_mol", "log_path", "out_path"])
        for r in results:
            w.writerow([r.ligand, r.status, r.best_affinity, r.log_path, r.out_path])

    print(f"\nWrote: {summary_csv}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())